import {
  Activity,
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Baby,
  Banknote,
  Bell,
  Bike,
  Boxes,
  Building2,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  ClipboardList,
  Clock,
  CreditCard,
  DoorOpen,
  FileText,
  Flag,
  Grid3x3,
  Hand,
  History,
  Home,
  Hourglass,
  LifeBuoy,
  LogOut,
  Map,
  MapPin,
  Megaphone,
  MoreHorizontal,
  Navigation,
  Package,
  PackageCheck,
  PackageOpen,
  Phone,
  PlusCircle,
  Rabbit,
  Receipt,
  RefreshCw,
  Route,
  Sailboat,
  ScanLine,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Ticket,
  Timer,
  TrendingUp,
  Truck,
  User,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wallet,
  Waves,
  X,
  Zap,
} from 'lucide-react-native'

import { COLORS } from '@/theme/tokens'

/**
 * Every glyph the apps may name, in one registry.
 *
 * Screens pass a name rather than importing lucide directly: it keeps icon choices reviewable in
 * one place, lets the API hand back an icon name as data, and means an unknown name degrades to a
 * parcel instead of crashing the render.
 */
const REGISTRY = {
  Activity,
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Baby,
  Banknote,
  Bell,
  Bike,
  Boxes,
  Building2,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  ClipboardList,
  Clock,
  CreditCard,
  DoorOpen,
  FileText,
  Flag,
  Grid3x3,
  Hand,
  History,
  Home,
  Hourglass,
  LifeBuoy,
  LogOut,
  Map,
  MapPin,
  Megaphone,
  MoreHorizontal,
  Navigation,
  Package,
  PackageCheck,
  PackageOpen,
  Phone,
  PlusCircle,
  Rabbit,
  Receipt,
  RefreshCw,
  Route,
  Sailboat,
  ScanLine,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Ticket,
  Timer,
  TrendingUp,
  Truck,
  User,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wallet,
  Waves,
  X,
  Zap,
} as const

export type IconName = keyof typeof REGISTRY

export function Icon({
  name,
  size = 20,
  color = COLORS.navy,
  strokeWidth = 2,
}: {
  name: IconName | string
  size?: number
  color?: string
  strokeWidth?: number
}) {
  const Glyph = REGISTRY[name as IconName] ?? Package
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} />
}
