export interface Country {
  name: string
  iso2: string
  dial: string
}

export const COUNTRIES: Country[] = [
  { name: 'Saudi Arabia', iso2: 'SA', dial: '+966' },
  { name: 'United Arab Emirates', iso2: 'AE', dial: '+971' },
  { name: 'Morocco', iso2: 'MA', dial: '+212' },
  { name: 'Egypt', iso2: 'EG', dial: '+20' },
  { name: 'Qatar', iso2: 'QA', dial: '+974' },
  { name: 'Kuwait', iso2: 'KW', dial: '+965' },
  { name: 'Bahrain', iso2: 'BH', dial: '+973' },
  { name: 'Oman', iso2: 'OM', dial: '+968' },
  { name: 'Jordan', iso2: 'JO', dial: '+962' },
  { name: 'Lebanon', iso2: 'LB', dial: '+961' },
  { name: 'Iraq', iso2: 'IQ', dial: '+964' },
  { name: 'Tunisia', iso2: 'TN', dial: '+216' },
  { name: 'Algeria', iso2: 'DZ', dial: '+213' },
  { name: 'Turkey', iso2: 'TR', dial: '+90' },
  { name: 'United Kingdom', iso2: 'GB', dial: '+44' },
  { name: 'United States', iso2: 'US', dial: '+1' },
  { name: 'Canada', iso2: 'CA', dial: '+1' },
  { name: 'France', iso2: 'FR', dial: '+33' },
  { name: 'Germany', iso2: 'DE', dial: '+49' },
  { name: 'Spain', iso2: 'ES', dial: '+34' },
  { name: 'Italy', iso2: 'IT', dial: '+39' },
  { name: 'Netherlands', iso2: 'NL', dial: '+31' },
  { name: 'Belgium', iso2: 'BE', dial: '+32' },
  { name: 'Switzerland', iso2: 'CH', dial: '+41' },
  { name: 'Sweden', iso2: 'SE', dial: '+46' },
  { name: 'Norway', iso2: 'NO', dial: '+47' },
  { name: 'Denmark', iso2: 'DK', dial: '+45' },
  { name: 'Portugal', iso2: 'PT', dial: '+351' },
  { name: 'Ireland', iso2: 'IE', dial: '+353' },
  { name: 'India', iso2: 'IN', dial: '+91' },
  { name: 'Pakistan', iso2: 'PK', dial: '+92' },
  { name: 'Bangladesh', iso2: 'BD', dial: '+880' },
  { name: 'Indonesia', iso2: 'ID', dial: '+62' },
  { name: 'Malaysia', iso2: 'MY', dial: '+60' },
  { name: 'Philippines', iso2: 'PH', dial: '+63' },
  { name: 'Singapore', iso2: 'SG', dial: '+65' },
  { name: 'China', iso2: 'CN', dial: '+86' },
  { name: 'Japan', iso2: 'JP', dial: '+81' },
  { name: 'South Korea', iso2: 'KR', dial: '+82' },
  { name: 'Australia', iso2: 'AU', dial: '+61' },
  { name: 'New Zealand', iso2: 'NZ', dial: '+64' },
  { name: 'South Africa', iso2: 'ZA', dial: '+27' },
  { name: 'Nigeria', iso2: 'NG', dial: '+234' },
  { name: 'Kenya', iso2: 'KE', dial: '+254' },
  { name: 'Brazil', iso2: 'BR', dial: '+55' },
  { name: 'Mexico', iso2: 'MX', dial: '+52' },
  { name: 'Argentina', iso2: 'AR', dial: '+54' },
  { name: 'Russia', iso2: 'RU', dial: '+7' },
]

export const DEFAULT_COUNTRY = COUNTRIES[0]
