import type { VersionChange, VersionLink } from '../models/index.js'

type Draft = Omit<VersionChange, 'checks' | 'issues'>

const change = (
  area: string,
  title: string,
  detail: string,
  roles: string[],
  howToTest: string[],
  expect: string,
  links: VersionLink[] = [],
): Draft => ({ area, title, detail, roles, howToTest, expect, links })

const AGENT = 'Sign in as agent.wayz@lockerflow.demo / Agent@123 (the Iran bag desk)'
const MOBILITY = 'Sign in as agent.gate1.wayz@lockerflow.demo / Agent@123 (the Gate 1 mobility desk)'
const CEO = 'Sign in as admin.wayz@lockerflow.demo / Admin@123'
const MANAGER = 'Sign in as manager.wayz@lockerflow.demo / Manager@123'
const HR = 'Sign in as hr.wayz@lockerflow.demo / People@123'
const COURIER = 'Sign in as courier.wayz@lockerflow.demo / Courier@123'
const ACCOUNTANT = 'Sign in as accountant.wayz@lockerflow.demo / Account@123'
const LAGOON_DESK = 'Sign in as welcome.wayz@lockerflow.demo / Lagoon@123 (the Mountain jetty desk)'

export const RELEASE_FIVE: Draft[] = [
  change(
    'Money',
    'Discount codes: printed in batches, redeemed at any desk',
    'The CEO creates a batch — a name, how many codes, the percentage, an optional expiry and which activities it works on — and the platform mints that many unique codes. A customer reads one out at any kiosk, the desk types it in, and the percentage comes off that sale. A code works once. A batch can be stopped, which kills every unused code and leaves the spent ones on the record.',
    ['CEO', 'Kiosk agent'],
    [
      CEO,
      'Open My company → Discount codes and press New batch',
      'Name it "Opening week", 50 codes, 25%, leave the activities empty, and create it',
      'Click the batch to read the codes, and export them as CSV to print',
      MOBILITY,
      'Open the till, start a scooter rental, and on the payment step press Discount code',
      'Type one of the codes and redeem it, then try the same code again',
    ],
    'The batch appears with its counts. Every code is unique, six characters after the dash, with no letters that read like digits. The first redemption takes 25% off the sale; the second attempt is refused as already used. Back on the batch, that code shows as redeemed against the booking it paid for. A desk agent cannot create a batch at all.',
    [{ label: 'Discount codes', to: '/admin/vouchers' }],
  ),
  change(
    'Money',
    'The receipt prints itself after a payment',
    'Whenever a payment goes through — at the counter, at the till queue or in a workspace — the slip goes straight to the printer, with nothing on screen to dismiss, so a busy desk cannot forget it and is not held up by it. The company can turn it off in its settings. The printed slip was also re-cut: the workspace no longer occupies the roll, so no metre of blank paper follows the receipt.',
    ['Kiosk agent'],
    [
      MOBILITY,
      'Open the till and sell an hour on a scooter',
      'Take the payment and watch the screen',
      'Open the booking and press Sales invoice, then Print, to see the same slip',
    ],
    'The payment is followed by "it printed itself" and the slip goes to the printer without covering the counter. In the print preview it is one narrow slip, 80 mm wide, with no dialog furniture and no long blank tail after the total.',
    [{ label: 'Till queue', to: '/till/queue' }],
  ),
  change(
    'Bookings',
    'A finished rental stops counting',
    'The countdown on a completed or returned booking froze on screen but kept ticking on some rows. The clock now stops where the session stopped — at the moment the asset came back — and every screen that shows a timer reads the same stopped value.',
    ['Kiosk agent', 'Manager'],
    [
      MOBILITY,
      'Rent a scooter, let it run past its hour, take the overtime, then mark it returned',
      'Open the booking and read the Operational session card',
      'Leave the page open for a minute',
    ],
    'The remaining time reads as stopped and greyed, and it does not move again. A rental still out on the road keeps counting normally.',
    [{ label: 'Bookings', to: '/bookings' }],
  ),
  change(
    'Money',
    'A typed amount cannot exceed what is owed',
    'Number fields that decide money — the split-payment amount, a discount percentage, the number of visitors on a boat — clamped only when you clicked away, so an impossible figure could be typed and quoted from. They now hold their bounds as you type.',
    ['Kiosk agent'],
    [
      LAGOON_DESK,
      'Open the till, pick an Abra and a boat with a few seats free',
      'In Visitors, type 500',
      MOBILITY,
      'Start a rental, go to the payment step, tick Split it and type a first part far bigger than the total',
    ],
    'Visitors snaps to the seats actually free on that boat. The split amount snaps to the total, and the rest-on line stays correct.',
    [],
  ),
  change(
    'Estate',
    'Sites, stations and people can be removed — softly',
    'Delete buttons now sit on a site, a station and a person, alongside the one on a desk. Nothing is erased: the record stops appearing and its history stays whole. A site with stations, a station with desks, assets, staff or live sessions, and a person with an open till are all refused with a plain reason.',
    ['CEO', 'Manager'],
    [
      CEO,
      'Open Estate → Sites & stations, add a site and a station under it',
      'Try to delete the site while the station is still there, then delete the station and try again',
      'Open Team, add a member, then delete them and look for them in the list',
    ],
    'The site refuses while it still holds a station and names the reason. Emptied, it goes. The deleted member drops off the team list, and their bookings, shifts and audit trail are still readable everywhere they appeared.',
    [{ label: 'Sites & stations', to: '/manager/organisation' }, { label: 'Team', to: '/manager/team' }],
  ),
  change(
    'Estate',
    'Venue types are yours to name',
    'The venue type on a site was a fixed list. Pick "+ Add a venue type" and type your own — water park, corniche, whatever the venue is. It is tidied into house style and joins the list for every site afterwards.',
    ['CEO', 'Manager'],
    [MANAGER, 'Open Estate → Sites & stations and add a site', 'Open the venue type list, choose + Add a venue type, and type "water park"', 'Save, then add a second site and open the list again'],
    'The first site is saved as WATER PARK, and the second site is offered it in the list next to the built-in types.',
    [{ label: 'Sites & stations', to: '/manager/organisation' }],
  ),
  change(
    'Delivery',
    'A courier never handles money, and never leaves a debt behind',
    'A delivery cannot be raised while anything is owed — on the booking that took the call or on any other kiosk joining the run. The desk takes the money first. The courier has no payment screen at all, and no delivery fee is charged.',
    ['Kiosk agent', 'Delivery agent'],
    [
      AGENT,
      'Find a booking that ran into overtime and press Send to customer',
      'Read the refusal, take the overtime at the counter, then raise the delivery again',
    ],
    'The first attempt is refused and names what is owed and where. Once the counter has taken it, the delivery is raised, and the courier task shows nothing to collect at the door.',
    [{ label: 'Bookings', to: '/bookings' }, { label: 'Kiosk deliveries', to: '/deliveries' }],
  ),
  change(
    'Money',
    'Discounts and free rides, with a reason and a ceiling',
    'The desk can take a percentage off a sale, or make it free, but only for a reason on the company list and only up to that reason’s ceiling. The CEO edits the reasons and their ceilings in the operating rules. Every discount is on the audit trail with who gave it and why.',
    ['Kiosk agent', 'CEO'],
    [
      CEO,
      'Open Operating rules and read the discount reasons',
      MOBILITY,
      'Start a rental, press Discount on the payment step, choose "Promotion" and ask for 80%',
      'Then choose "VIP / SELA member" and tick Free ride',
    ],
    'Promotion refuses anything over its ceiling and says so. The free ride leaves only the refundable deposit to settle, and the sale closes with just that.',
    [{ label: 'Operating rules', to: '/admin/rules' }],
  ),
  change(
    'Money',
    'One sale, two ways to pay',
    'A customer can settle part in cash and the rest on the card. Tick Split it, set the first amount, choose the method for the rest, and both land on the same sale — the cash part in the drawer, the card part on the scheme it was taken on.',
    ['Kiosk agent'],
    [MOBILITY, 'Open the till and sell an hour on a scooter', 'On the payment step tick Split it, put half in cash, and leave the rest on MADA', 'Confirm, then open the booking and read what was paid'],
    'Both parts are recorded against the sale, the order shows as paid, and the drawer only counts the cash half.',
    [{ label: 'Till queue', to: '/till/queue' }],
  ),
  change(
    'Bookings',
    'Nothing moves until the customer is confirmed',
    'Payment, handing bags back and raising a delivery all refuse unless the customer confirmed a code in the last half hour. Coming back into overtime spends the old confirmation, so a customer who left and returned is checked again.',
    ['Kiosk agent'],
    [
      AGENT,
      'Store a bag, confirm the customer, then let the booking run into overtime',
      'Try to hand the bags back',
      'Take the overtime at the counter and try again',
      'Confirm the customer once more and try a third time',
    ],
    'Retrieval is refused while the overtime is unpaid. Paid but unconfirmed it is still refused — the old check no longer counts. Only after a fresh confirmation do the bags come out.',
    [{ label: 'Bookings', to: '/bookings' }],
  ),
  change(
    'Assets',
    'An incident takes the asset out of service and closes the booking',
    'Reporting damage on a live rental closes the session and moves the unit to maintenance in one step, so a broken scooter cannot be rented again while the report is open.',
    ['Kiosk agent', 'Manager'],
    [MOBILITY, 'Rent a scooter and hand it over', 'Open the booking and press Incident, choose Asset damage and describe it', 'Open Assets and find that scooter'],
    'The booking closes and the scooter reads as in maintenance, out of the pool, until a lead resolves the incident.',
    [{ label: 'Assets', to: '/assets' }],
  ),
  change(
    'Pricing',
    'Products carry an Arabic name and an icon',
    'A product can be given its Arabic name and an emoji, so the Arabic counter reads properly and the tiles are recognisable at a glance.',
    ['CEO', 'Manager', 'HR'],
    [HR, 'Open Pricing and edit a product', 'Give it an Arabic name and an icon, and save', AGENT, 'Switch the platform to Arabic and open the counter'],
    'The tile shows the icon and the Arabic name, and the invoice prints the Arabic name too.',
    [{ label: 'Pricing', to: '/manager/pricing' }],
  ),
  change(
    'Bookings',
    'A half-finished sale is still there when you come back',
    'Tapping another menu item mid-sale used to lose everything on the bag counter — the customer, the bags, the plan and the quote. Every counter now keeps a half-finished sale in the tab and picks it up where it was left, with a line saying so and a button to start a new one instead.',
    ['Kiosk agent'],
    [
      AGENT,
      'Open Shop & Drop, choose a customer, add two bags and take it as far as the payment step',
      'Click Bookings in the menu, then come back to Shop & Drop',
    ],
    'The sale is exactly where you left it, with the same quote, and a line saying it was picked up where you left off. Starting a new one is one button away.',
    [{ label: 'Shop & Drop', to: '/shop-drop' }],
  ),
  change(
    'Bookings',
    'A code answered by email counts, and a stale confirmation stops looking valid',
    'The confirmation box can send the code by WhatsApp or by email. A code answered by email was not being recorded as proof, so the tick went green and the payment was then refused. Both routes count now, and the green tick expires with the confirmation itself rather than staying green past it.',
    ['Kiosk agent'],
    [
      AGENT,
      'Start a bag drop for a customer who has an email on file',
      'On the payment step switch the confirmation box to Email, send the code and read it back',
      'Tick Split it, put half in cash, and confirm the payment',
    ],
    'The split payment goes through. Before this, an email confirmation left the sale refused with "Confirm the customer before taking their money" even though the box showed the customer as verified.',
    [],
  ),
  change(
    'Money',
    'A discount is money never taken, and the books say so',
    'A discount or a redeemed code is a real line on the order rather than a hidden adjustment, so every downstream figure follows it: the till expects the discounted cash, the accountant’s ledger and the till transaction carry the same amount, and the list price cannot be charged afterwards.',
    ['Kiosk agent', 'Accountant', 'Manager'],
    [
      AGENT,
      'Sell an hour on a scooter and redeem a 25% code against it',
      'Take the payment in cash, then open the till and read the expected cash',
      ACCOUNTANT,
      'Open Settlement → Payments and find that booking',
    ],
    'The till expects the discounted amount, not the list price, and the accountant sees the same figure. The audit trail names who gave the discount and against what.',
    [{ label: 'Till', to: '/shift' }, { label: 'Payments', to: '/accounting/settlement/payments' }],
  ),
  change(
    'Shop & Drop',
    'Bags go to an exit gate, and the gate hands them over',
    'A bag drop is charged once, at the desk that takes the bags in. From there the bags are sent to an exit gate; the customer collects them from the agent at that gate, and if they have run into overtime they pay that agent. The courier does nothing but move the bags — no codes, no fees, no money. Any desk can be marked as an exit gate on the estate page.',
    ['Kiosk agent', 'Delivery agent'],
    [
      AGENT,
      'Store a bag for a customer, then open the booking and press Send to customer',
      'Choose An exit gate, pick Gate 1, and raise it',
      COURIER,
      'Pick the job up, and at the desk ask them to hand the bags over',
      AGENT,
      'Confirm the courier and release the bags, then scan them as the courier',
      'Mark it delivered',
      'Sign in as the Gate 1 agent and look at the bookings list',
    ],
    'The booking leaves the desk that took it in and appears at Gate 1, still open, with the bags shown as held by that gate. The Gate 1 agent checks the customer, takes any overtime, and closes it. Nothing is charged for the move itself.',
    [{ label: 'Bookings', to: '/bookings' }, { label: 'Kiosk deliveries', to: '/deliveries' }],
  ),
  change(
    'Delivery',
    'Releasing bags is one confirmation, not a round trip',
    'The courier no longer has to ask before the desk can act. Whoever is at the counter confirms the courier in front of them and hands the bags over in a single step, stamped with their name and the time. The courier can still tell the desk they have arrived, but nothing waits on it.',
    ['Kiosk agent', 'Delivery agent'],
    [AGENT, 'Open Kiosk deliveries with a courier assigned to a job', 'Press Check courier and confirm, without the courier pressing anything first'],
    'The bags are released on that one confirmation, and the timeline records who released them and when.',
    [{ label: 'Kiosk deliveries', to: '/deliveries' }],
  ),
  change(
    'Money',
    'Free rides and discounts are a tick box, and they are all reported',
    'On the Mobility and Lagoon counters a tick box opens a reason list — the reason is required, never optional — and either a percentage or a free ride. Every one is recorded against the booking with who gave it and why, summed on the manager dashboard, and listed in a report with breakdowns by reason and by agent. The reasons themselves are edited by the CEO in Operating rules.',
    ['Kiosk agent', 'Manager', 'CEO'],
    [
      CEO,
      'Open Operating rules and look at "Why a discount may be given" — add or edit a reason and save',
      MOBILITY,
      'Start a rental and on the payment step tick "Free ride or discount for this customer"',
      'Try to apply without choosing a reason, then choose one and tick Free ride',
      MANAGER,
      'Open the dashboard, then Reports → Free rides & discounts',
    ],
    'Nothing can be given away without a reason. The dashboard shows what was given away today, and the report breaks it down by reason and by agent, with a CSV export.',
    [
      { label: 'Operating rules', to: '/admin/rules' },
      { label: 'Reports', to: '/manager/reports' },
    ],
  ),
]

export const RELEASE_FIVE_META = {
  _id: 'ver-0005',
  number: '2026.09.08',
  name: 'The client’s list, end to end',
  summary:
    'The twenty-four points from the 8 September review and the follow-ups that came back the same day. Bags now go to an exit gate and are collected there; releasing them is one stamped confirmation; free rides and discounts are a tick box with a required reason, summed on the dashboard and reported. Plus discount codes you can print in batches, receipts that print themselves, and finished rentals that stop counting.',
  releasedAt: new Date('2026-09-08T06:00:00.000Z'),
  highlights: [
    'Bags sent to an exit gate, collected there, with the courier carrying no money',
    'Free rides and discounts: a tick box, a required reason, and a report that sums them',
    'Discount codes minted in batches and redeemed at any desk',
    'The receipt prints itself, on a slip that fits the roll',
    'A finished rental stops counting',
    'Sites, stations and people deleted softly, history intact',
    'No typed amount can exceed what is owed',
  ],
}
